// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL7KVw6Cwy5ZXebPIah2Peuslqm0H084Y',
    appId: '1:75447501137:web:2d0bc6657a53a51dafd370',
    messagingSenderId: '75447501137',
    projectId: 'vrindavan-tiffin',
    authDomain: 'vrindavan-tiffin.firebaseapp.com',
    storageBucket: 'vrindavan-tiffin.appspot.com',
    measurementId: 'G-E1DSTZDNGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkHoqJipinsZCiYTzkx5ufq13kS7o8tmU',
    appId: '1:75447501137:android:b2afbf82e8bf23bbafd370',
    messagingSenderId: '75447501137',
    projectId: 'vrindavan-tiffin',
    storageBucket: 'vrindavan-tiffin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3VYnoqU_jYuPzEAgdUB-LSHpaTuJDZFQ',
    appId: '1:75447501137:ios:d58ed84831901017afd370',
    messagingSenderId: '75447501137',
    projectId: 'vrindavan-tiffin',
    storageBucket: 'vrindavan-tiffin.appspot.com',
    iosBundleId: 'com.vrindavan.tiffin',
  );

}